name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm install
    - name: Build TypeScript files
      run: npx tsc
    - name: Start Cypress test
      run: npx cypress run
